name: Wdrożenie Stosu Observability i AKS

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Deploy_Infrastructure_and_Monitoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zalogowanie do Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Inicjalizacja i budowa Terraform
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Pobranie poświadczeń klastra AKS
        run: az aks get-credentials --resource-group RG-Observability-Lab --name aks-observability --overwrite-existing

      - name: Instalacja Prometheusa i Grafany (Helm)
        run: |
          # Dodanie rynkowego repozytorium Prometheus Community
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          # Instalacja potężnego stosu monitorującego (tworzy m.in. Grafanę)
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace

      - name: Wdrożenie aplikacji i generatora ruchu
        run: |
          kubectl apply -f ./k8s/app.yaml
          kubectl apply -f ./k8s/load-generator.yaml